#ifndef PARSE_ELEM_TYPE_H_INCLUDED
#define PARSE_ELEM_TYPE_H_INCLUDED

enum class ParseElementType {
    TYPE_INVALID,
	TYPE_EMPTY,

    TYPE_HTML_BLOCK,
    TYPE_CODE_BLOCK,
    TYPE_HEADER_ATX,
    TYPE_HEADER_SETEXT,
    TYPE_HORIZON,
    TYPE_QUOTE,
    TYPE_LIST_UNORDERED,
    TYPE_LIST_ORDERED,
    TYPE_PARAGRAPH,
};

#endif // PARSE_ELEM_TYPE_H_INCLUDED
