#ifndef PARSE_TYPE_H_INCLUDED
#define PARSE_TYPE_H_INCLUDED

enum class ParseElemType {
    ELEM_INVALID,
    ELEM_TEXT,
    ELEM_PARAGRAPH,
    ELEM_HTML_BLOCK,
    ELEM_HTML_INLINE,
    ELEM_HEADER_ATX,
    ELEM_HEADER_SETEXT,
    ELEM_BLOCK_QUOTE,
    ELEM_LIST_UNORDERED,
    ELEM_LIST_ORDERED,
    ELEM_CODE_BLOCK,
    ELEM_HORIZONTAL_RULE,
    ELEM_LINK_INLINE,
    ELEM_LINK_REFERENCE,
    ELEM_LINK_LABEL,
    ELEM_EMPHASIS,
    ELEM_STRONG,
    ELEM_INLINE_CODE,
    ELEM_IMAGE,
};

#endif // PARSE_TYPE_H_INCLUDED
